name: fml
description: "Flutter Minecraft Launcher"
publish_to: 'none'
version: 1.4.0+6

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  cupertino_icons: ^1.0.8
  path: ^1.9.1
  shared_preferences: ^2.5.3
  crypto: ^3.0.6
  file_selector: ^1.0.3
  system_info2: ^4.0.0
  file_picker: ^10.2.4
  flutter_launcher_icons: ^0.14.4
  dio: ^5.9.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  flutter_local_notifications: ^19.4.0
  synchronized: ^3.4.0
  archive: ^4.0.7
  package_info_plus: ^9.0.0
  flutter_markdown: ^0.7.7+1
  uuid: ^4.5.1
  flutter_gbk2utf8: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/icon/icon.png
    - assets/img/logo/flutter.png
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansCJKsc-VF.ttf
